-- ═══════════════════════════════════════════════════════════════════════
-- Actualización: inventario real del negocio (migrado desde INVENTARIO.xlsx)
-- Añade 'ubicacion' y 'marca' a productos, crea el catálogo de ubicaciones
-- (las pestañas del Excel = lugares físicos) e importa los ítems del inventario.
--
-- Ejecutar UNA sola vez sobre una BD sns_principal YA instalada.
-- (En una instalación nueva las columnas y el catálogo ya vienen en el script
--  completo; aquí van además los datos de operación.)
-- ═══════════════════════════════════════════════════════════════════════
USE sns_principal;

-- 1) Nuevas dimensiones del inventario físico -------------------------------
ALTER TABLE productos
  ADD COLUMN ubicacion VARCHAR(60) DEFAULT NULL AFTER categoria,
  ADD COLUMN marca     VARCHAR(60) DEFAULT NULL AFTER ubicacion;

CREATE INDEX idx_productos_ubicacion ON productos (ubicacion);

-- 2) Catálogo de ubicaciones (reutilizable, como categorias_producto) -------
CREATE TABLE IF NOT EXISTS ubicaciones (
  id INT AUTO_INCREMENT PRIMARY KEY,
  nombre VARCHAR(60) NOT NULL UNIQUE,
  orden  INT NOT NULL DEFAULT 100
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

INSERT INTO ubicaciones (nombre, orden) VALUES
  ('Esmaltero semipermanente', 10),
  ('Esmaltero gato y painting', 20),
  ('Esmaltero secado rápido', 30),
  ('Esmaltero tradicional', 40),
  ('Recepción', 50),
  ('Pestañas', 60)
ON DUPLICATE KEY UPDATE orden = VALUES(orden);

-- 3) Categorías del Excel al catálogo reutilizable --------------------------
INSERT IGNORE INTO categorias_producto (nombre) VALUES
  ('ACRILICO'),
  ('ALCOHOL'),
  ('ARTIFICIAL'),
  ('BASE'),
  ('BROCAS'),
  ('BUIDER'),
  ('CANULAS'),
  ('CHOCOLATERAPIA'),
  ('COLOR GEL AMARILLOS SEMI'),
  ('COLOR GEL AZULES SEMI'),
  ('COLOR GEL BEIGE SEMI'),
  ('COLOR GEL BLANCO SEMI'),
  ('COLOR GEL CRISTAL'),
  ('COLOR GEL EFECTO'),
  ('COLOR GEL ESCARCHADO'),
  ('COLOR GEL FLASH'),
  ('COLOR GEL FNAILS'),
  ('COLOR GEL GRIS SEMI'),
  ('COLOR GEL MARRON SEMI'),
  ('COLOR GEL MORADOS SEMI'),
  ('COLOR GEL NARANJA SEMI'),
  ('COLOR GEL NEGRO SEMI'),
  ('COLOR GEL NEON SEMI'),
  ('COLOR GEL NUDE SEMI'),
  ('COLOR GEL ROJOS SEMI'),
  ('COLOR GEL ROSAS SEMI'),
  ('COLOR GEL TERMICOS'),
  ('COLOR GEL VERDES SEMI'),
  ('CREMAS'),
  ('DECORACION'),
  ('EFECTO'),
  ('ELASTIC'),
  ('ESMALTE'),
  ('FINALIZADOR'),
  ('GEL SOLIDO'),
  ('HERRAMIENTAS'),
  ('KIT'),
  ('LIMA'),
  ('LIMAS'),
  ('LIQUIDOS'),
  ('MOLDES'),
  ('OJO DE GATO'),
  ('PAINTING ESCARCHADO'),
  ('PAINTING GEL'),
  ('PALOS'),
  ('PINCELES'),
  ('PLATINUM'),
  ('PRESS ON'),
  ('REMOVEDOR'),
  ('REPARADOR'),
  ('RUBBER'),
  ('SECADO RAPIDO'),
  ('SECADO RAPIDO COLOR GEL'),
  ('SECADO RAPIDO ESCARCHADO'),
  ('SECADO RAPIDO TRASLUCIDO'),
  ('SEMIPERMANENTE'),
  ('TIPS'),
  ('TOALLATAS'),
  ('TRADICIONAL'),
  ('TRADICIONAL ESCARCHADO'),
  ('TRADICIONAL ESMALTE'),
  ('TRADICIONAL TRASLUCIDO'),
  ('TRASLUCIDOS');

-- 4) Ítems del inventario (515 en total) ----------------------------------
INSERT INTO productos (nombre, categoria, ubicacion, marca, unidad, stock, stock_minimo, fecha_compra) VALUES
  ('BASE 04', 'TRASLUCIDOS', 'Esmaltero semipermanente', 'LATIN NAILS', 'unidad', 0, 0, '2025-08-16'),
  ('LL02', 'TRASLUCIDOS', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 2, 0, '2025-08-16'),
  ('030 CLASSIC SKIN', 'TRASLUCIDOS', 'Esmaltero semipermanente', 'ORGANIC', 'unidad', 1, 0, '2025-08-16'),
  ('115 LIGTH ROSE', 'TRASLUCIDOS', 'Esmaltero semipermanente', 'ORGANIC', 'unidad', 1, 0, '2025-08-16'),
  ('116 GARDEN ROSE', 'TRASLUCIDOS', 'Esmaltero semipermanente', 'ORGANIC', 'unidad', 1, 0, '2025-08-16'),
  ('117 CREAMY ROSE', 'TRASLUCIDOS', 'Esmaltero semipermanente', 'ORGANIC', 'unidad', 1, 0, '2025-08-16'),
  ('118 CORAL ROSE', 'TRASLUCIDOS', 'Esmaltero semipermanente', 'ORGANIC', 'unidad', 2, 0, '2025-08-16'),
  ('NOVIA', 'TRASLUCIDOS', 'Esmaltero semipermanente', 'MASGLO', 'unidad', 1, 0, '2025-08-16'),
  ('TRENDY', 'TRASLUCIDOS', 'Esmaltero semipermanente', 'MASGLO', 'unidad', 1, 0, '2025-08-16'),
  ('SHIMER FRE 02', 'TRASLUCIDOS', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 1, 0, '2025-08-16'),
  ('SHIMER FRE 64', 'TRASLUCIDOS', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 1, 0, '2025-08-16'),
  ('9066', 'TRASLUCIDOS', 'Esmaltero semipermanente', 'CANNI', 'unidad', 1, 0, '2025-12-12'),
  ('9054', 'TRASLUCIDOS', 'Esmaltero semipermanente', 'CANNI', 'unidad', 1, 0, '2025-12-12'),
  ('LOVE KISS 092', 'TRASLUCIDOS', 'Esmaltero semipermanente', 'ORGANIC', 'unidad', 3, 0, '2026-02-03'),
  ('FRE64', 'TRASLUCIDOS', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 1, 0, '2026-02-03'),
  ('FRE18', 'TRASLUCIDOS', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 3, 0, '2026-02-03'),
  ('SMC056', 'TRASLUCIDOS', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 1, 0, '2026-02-03'),
  ('SC1153', 'TRASLUCIDOS', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 1, 0, '2026-02-03'),
  ('FRE31', 'TRASLUCIDOS', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 2, 0, '2026-02-03'),
  ('COLOR', 'RUBBER', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 2, 0, '2025-08-16'),
  ('COLOR', 'RUBBER', 'Esmaltero semipermanente', 'ORGANIC', 'unidad', 1, 0, '2026-02-03'),
  ('VITAL2', 'REPARADOR', 'Esmaltero semipermanente', 'ORGANIC', 'unidad', 2, 0, '2025-08-16'),
  ('BLOOMING', 'DECORACION', 'Esmaltero semipermanente', 'RONIKI', 'unidad', 1, 0, '2025-08-16'),
  ('BLOOMING', 'DECORACION', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 1, 0, '2026-02-03'),
  ('TOP COAT MATE', 'FINALIZADOR', 'Esmaltero semipermanente', 'ORGANIC', 'unidad', 2, 0, '2025-08-16'),
  ('GALAXY MAGNETIC 077', 'EFECTO', 'Esmaltero semipermanente', 'ORGANIC', 'unidad', 1, 0, '2026-02-03'),
  ('GALAXY MALVA 079', 'EFECTO', 'Esmaltero semipermanente', 'ORGANIC', 'unidad', 1, 0, '2026-02-03'),
  ('GEL 173', 'EFECTO', 'Esmaltero semipermanente', 'NAILISTAS', 'unidad', 1, 0, '2026-02-03'),
  ('TRASNFER', 'DECORACION', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 1, 0, '2026-02-03'),
  ('031 CLASSIC TRAPE', 'COLOR GEL NUDE SEMI', 'Esmaltero semipermanente', 'ORGANIC', 'unidad', 1, 0, '2026-02-03'),
  ('108 TRUE CHOCOLATE', 'COLOR GEL NUDE SEMI', 'Esmaltero semipermanente', 'ORGANIC', 'unidad', 1, 0, '2025-08-16'),
  ('107 TRUE COFFE', 'COLOR GEL NUDE SEMI', 'Esmaltero semipermanente', 'ORGANIC', 'unidad', 1, 0, '2025-08-16'),
  ('028 CLASSIC MOCA', 'COLOR GEL NUDE SEMI', 'Esmaltero semipermanente', 'ORGANIC', 'unidad', 1, 0, '2025-08-16'),
  ('105 TRUE LIPS', 'COLOR GEL NUDE SEMI', 'Esmaltero semipermanente', 'ORGANIC', 'unidad', 1, 0, '2025-08-16'),
  ('MATRIMONIO', 'COLOR GEL NUDE SEMI', 'Esmaltero semipermanente', 'MASGLO', 'unidad', 1, 0, '2025-08-16'),
  ('9045', 'COLOR GEL NUDE SEMI', 'Esmaltero semipermanente', 'CANNI', 'unidad', 1, 0, '2026-02-03'),
  ('29', 'COLOR GEL NUDE SEMI', 'Esmaltero semipermanente', 'CANNI', 'unidad', 1, 0, '2026-02-03'),
  ('34', 'COLOR GEL NUDE SEMI', 'Esmaltero semipermanente', 'CANNI', 'unidad', 1, 0, '2026-02-03'),
  ('3', 'COLOR GEL NUDE SEMI', 'Esmaltero semipermanente', 'CANNI', 'unidad', 1, 0, '2026-02-03'),
  ('010 ICE BLUE', 'COLOR GEL AZULES SEMI', 'Esmaltero semipermanente', 'ORGANIC', 'unidad', 2, 0, '2025-08-16'),
  ('022 SAILOR SEA', 'COLOR GEL AZULES SEMI', 'Esmaltero semipermanente', 'ORGANIC', 'unidad', 2, 0, '2025-08-16'),
  ('164 CIEL', 'COLOR GEL AZULES SEMI', 'Esmaltero semipermanente', 'ORGANIC', 'unidad', 2, 0, '2025-08-16'),
  ('JL05', 'COLOR GEL AZULES SEMI', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 1, 0, '2025-08-16'),
  ('176', 'COLOR GEL AZULES SEMI', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 1, 0, '2025-08-16'),
  ('042 IMPERIAL BLUE', 'COLOR GEL AZULES SEMI', 'Esmaltero semipermanente', 'ORGANIC', 'unidad', 1, 0, '2025-08-16'),
  ('165 STEEBLE', 'COLOR GEL AZULES SEMI', 'Esmaltero semipermanente', 'ORGANIC', 'unidad', 1, 0, '2025-08-16'),
  ('O20 MIDNIGTH BLUE', 'COLOR GEL AZULES SEMI', 'Esmaltero semipermanente', 'ORGANIC', 'unidad', 2, 0, '2025-08-16'),
  ('150 PASTEL AQUA', 'COLOR GEL AZULES SEMI', 'Esmaltero semipermanente', 'ORGANIC', 'unidad', 1, 0, '2025-08-16'),
  ('152 PASTEL MIND', 'COLOR GEL VERDES SEMI', 'Esmaltero semipermanente', 'ORGANIC', 'unidad', 2, 0, '2025-08-16'),
  ('20', 'COLOR GEL VERDES SEMI', 'Esmaltero semipermanente', 'ROSALIND', 'unidad', 1, 0, '2025-08-16'),
  ('41', 'COLOR GEL VERDES SEMI', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 1, 0, '2025-08-16'),
  ('100 FLORAL LEAVES', 'COLOR GEL VERDES SEMI', 'Esmaltero semipermanente', 'ORGANIC', 'unidad', 1, 0, '2025-08-16'),
  ('102 FLORAL GRASS', 'COLOR GEL VERDES SEMI', 'Esmaltero semipermanente', 'ORGANIC', 'unidad', 1, 0, '2025-08-16'),
  ('SC1321', 'COLOR GEL VERDES SEMI', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 0, 0, '2025-08-16'),
  ('47', 'COLOR GEL VERDES SEMI', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 1, 0, '2025-08-16'),
  ('C238', 'COLOR GEL VERDES SEMI', 'Esmaltero semipermanente', 'CANNI', 'unidad', 1, 0, '2025-08-16'),
  ('LS03', 'COLOR GEL VERDES SEMI', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 1, 0, '2026-02-03'),
  ('128', 'COLOR GEL NEGRO SEMI', 'Esmaltero semipermanente', 'LATIN NAILS', 'unidad', 2, 0, '2025-08-16'),
  ('SMC144', 'COLOR GEL NEGRO SEMI', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 2, 0, '2025-08-16'),
  ('040 IMPERIAL BLACK', 'COLOR GEL NEGRO SEMI', 'Esmaltero semipermanente', 'ORGANIC', 'unidad', 1, 0, '2025-08-16'),
  ('025 SAILOR WHITE', 'COLOR GEL BLANCO SEMI', 'Esmaltero semipermanente', 'ORGANIC', 'unidad', 2, 0, '2025-08-16'),
  ('SMC 138', 'COLOR GEL BLANCO SEMI', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 2, 0, '2025-08-16'),
  ('WHITE', 'COLOR GEL BLANCO SEMI', 'Esmaltero semipermanente', 'MIA SECRET', 'unidad', 1, 0, '2025-08-16'),
  ('167 MOON WHITE', 'COLOR GEL BLANCO SEMI', 'Esmaltero semipermanente', 'ORGANIC', 'unidad', 1, 0, '2025-08-16'),
  ('THREAD PEARL GEL 01', 'COLOR GEL BLANCO SEMI', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 1, 0, '2026-02-03'),
  ('140', 'COLOR GEL MARRON SEMI', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 1, 0, '2025-08-16'),
  ('QQ08', 'COLOR GEL MARRON SEMI', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 1, 0, '2025-08-16'),
  ('SMC041', 'COLOR GEL MARRON SEMI', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 1, 0, '2025-08-16'),
  ('QQ04', 'COLOR GEL MARRON SEMI', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 1, 0, '2025-08-16'),
  ('QQ10', 'COLOR GEL MARRON SEMI', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 1, 0, '2025-08-16'),
  ('094 LOVE SONG', 'COLOR GEL MARRON SEMI', 'Esmaltero semipermanente', 'ORGANIC', 'unidad', 1, 0, '2025-08-16'),
  ('SMC 006', 'COLOR GEL MARRON SEMI', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 1, 0, '2025-08-16'),
  ('9015', 'COLOR GEL MARRON SEMI', 'Esmaltero semipermanente', 'CANNI', 'unidad', 1, 0, '2025-08-16'),
  ('82', 'COLOR GEL MARRON SEMI', 'Esmaltero semipermanente', 'LIMEGIRL', 'unidad', 1, 0, '2025-08-16'),
  ('83', 'COLOR GEL MARRON SEMI', 'Esmaltero semipermanente', 'LIMEGIRL', 'unidad', 1, 0, '2025-08-16'),
  ('119', 'COLOR GEL MARRON SEMI', 'Esmaltero semipermanente', 'LIMEGIRL', 'unidad', 1, 0, '2025-08-16'),
  ('147', 'COLOR GEL MARRON SEMI', 'Esmaltero semipermanente', 'LIMEGIRL', 'unidad', 1, 0, '2025-08-16'),
  ('148', 'COLOR GEL MARRON SEMI', 'Esmaltero semipermanente', 'LIMEGIRL', 'unidad', 1, 0, '2025-08-16'),
  ('149', 'COLOR GEL MARRON SEMI', 'Esmaltero semipermanente', 'LIMEGIRL', 'unidad', 0, 0, '2025-08-16'),
  ('DARK CHOCOLATE 160', 'COLOR GEL MARRON SEMI', 'Esmaltero semipermanente', 'ORGANIC', 'unidad', 1, 0, '2025-08-16'),
  ('205', 'COLOR GEL GRIS SEMI', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 1, 0, '2025-08-16'),
  ('SMC103', 'COLOR GEL GRIS SEMI', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 1, 0, '2025-08-16'),
  ('SC1165', 'COLOR GEL ROSAS SEMI', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 1, 0, '2025-08-16'),
  ('DMC 500', 'COLOR GEL ROSAS SEMI', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 1, 0, '2025-08-16'),
  ('SMC005', 'COLOR GEL ROSAS SEMI', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 1, 0, '2025-08-16'),
  ('029 CLASSIC BLUSH', 'COLOR GEL ROSAS SEMI', 'Esmaltero semipermanente', 'ORGANIC', 'unidad', 1, 0, '2025-08-16'),
  ('106 TRUE ALMOND', 'COLOR GEL ROSAS SEMI', 'Esmaltero semipermanente', 'ORGANIC', 'unidad', 1, 0, '2025-08-16'),
  ('014 ICE PINK', 'COLOR GEL ROSAS SEMI', 'Esmaltero semipermanente', 'ORGANIC', 'unidad', 1, 0, '2025-08-16'),
  ('015 ICE DAISY', 'COLOR GEL ROSAS SEMI', 'Esmaltero semipermanente', 'ORGANIC', 'unidad', 1, 0, '2025-08-16'),
  ('158 PASTEL PINK', 'COLOR GEL ROSAS SEMI', 'Esmaltero semipermanente', 'ORGANIC', 'unidad', 1, 0, '2025-08-16'),
  ('047 BUBBLE CANDY', 'COLOR GEL ROSAS SEMI', 'Esmaltero semipermanente', 'ORGANIC', 'unidad', 1, 0, '2025-08-16'),
  ('H963', 'COLOR GEL MORADOS SEMI', 'Esmaltero semipermanente', 'LATIN NAILS', 'unidad', 1, 0, '2025-08-16'),
  ('159 PASTEL LILAC', 'COLOR GEL MORADOS SEMI', 'Esmaltero semipermanente', 'ORGANIC', 'unidad', 2, 0, '2025-08-16'),
  ('A905', 'COLOR GEL MORADOS SEMI', 'Esmaltero semipermanente', 'ROSALIND', 'unidad', 1, 0, '2025-08-16'),
  ('019 MIDNIGT PUEPLE', 'COLOR GEL MORADOS SEMI', 'Esmaltero semipermanente', 'ORGANIC', 'unidad', 1, 0, '2025-08-16'),
  ('17', 'COLOR GEL MORADOS SEMI', 'Esmaltero semipermanente', 'ROSALIND', 'unidad', 1, 0, '2025-08-16'),
  ('149', 'COLOR GEL MORADOS SEMI', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 1, 0, '2025-08-16'),
  ('018 MIDNIGHT FLUSHA', 'COLOR GEL MORADOS SEMI', 'Esmaltero semipermanente', 'ORGANIC', 'unidad', 1, 0, '2025-08-16'),
  ('126 AMETHYST', 'COLOR GEL MORADOS SEMI', 'Esmaltero semipermanente', 'ORGANIC', 'unidad', 1, 0, '2025-08-16'),
  ('99 FLORAL BUGAMBILIA', 'COLOR GEL MORADOS SEMI', 'Esmaltero semipermanente', 'ORGANIC', 'unidad', 1, 0, '2025-08-16'),
  ('22', 'COLOR GEL MORADOS SEMI', 'Esmaltero semipermanente', 'CANNI', 'unidad', 1, 0, '2025-08-16'),
  ('48 BUBBLE GREPE', 'COLOR GEL MORADOS SEMI', 'Esmaltero semipermanente', 'ORGANIC', 'unidad', 1, 0, '2025-08-16'),
  ('12 ICE LILAC', 'COLOR GEL MORADOS SEMI', 'Esmaltero semipermanente', 'ORGANIC', 'unidad', 1, 0, '2025-08-16'),
  ('021 MIDNIGTH SCARLET', 'COLOR GEL MORADOS SEMI', 'Esmaltero semipermanente', 'ORGANIC', 'unidad', 1, 0, '2025-08-16'),
  ('124 MERLOT', 'COLOR GEL ROJOS SEMI', 'Esmaltero semipermanente', 'ORGANIC', 'unidad', 1, 0, '2025-08-16'),
  ('174 CHERRY', 'COLOR GEL ROJOS SEMI', 'Esmaltero semipermanente', 'ORGANIC', 'unidad', 1, 0, '2025-08-16'),
  ('098 FLORAL ROSE', 'COLOR GEL ROJOS SEMI', 'Esmaltero semipermanente', 'ORGANIC', 'unidad', 1, 0, '2025-08-16'),
  ('101 FLORAL LOTUS', 'COLOR GEL ROJOS SEMI', 'Esmaltero semipermanente', 'ORGANIC', 'unidad', 1, 0, '2025-08-16'),
  ('PX031', 'COLOR GEL ROJOS SEMI', 'Esmaltero semipermanente', 'ROSALIND', 'unidad', 1, 0, '2025-08-16'),
  ('ROJO', 'COLOR GEL ROJOS SEMI', 'Esmaltero semipermanente', 'UTOPIC', 'unidad', 1, 0, '2025-08-16'),
  ('044 IMPERIAL VELVET', 'COLOR GEL ROJOS SEMI', 'Esmaltero semipermanente', 'ORGANIC', 'unidad', 2, 0, '2025-08-16'),
  ('097 FLORAL DASEY', 'COLOR GEL ROJOS SEMI', 'Esmaltero semipermanente', 'ORGANIC', 'unidad', 1, 0, '2025-08-16'),
  ('024 SAILOR CARMESI', 'COLOR GEL ROJOS SEMI', 'Esmaltero semipermanente', 'ORGANIC', 'unidad', 1, 0, '2025-08-16'),
  ('1', 'COLOR GEL ROJOS SEMI', 'Esmaltero semipermanente', 'CANNI', 'unidad', 1, 0, '2025-08-16'),
  ('13', 'COLOR GEL ROJOS SEMI', 'Esmaltero semipermanente', 'CANNI', 'unidad', 1, 0, '2025-08-16'),
  ('C135', 'COLOR GEL ROJOS SEMI', 'Esmaltero semipermanente', 'CANNI', 'unidad', 1, 0, '2025-08-19'),
  ('JH05', 'COLOR GEL ROJOS SEMI', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 2, 0, '2026-02-03'),
  ('JJ04', 'COLOR GEL ROJOS SEMI', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 1, 0, NULL),
  ('JJ07', 'COLOR GEL ROJOS SEMI', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 1, 0, NULL),
  ('JJ08', 'COLOR GEL ROJOS SEMI', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 1, 0, NULL),
  ('SMC123', 'COLOR GEL ROJOS SEMI', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 1, 0, NULL),
  ('SMC047', 'COLOR GEL BEIGE SEMI', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 1, 0, '2026-02-03'),
  ('109', 'COLOR GEL AMARILLOS SEMI', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 1, 0, '2025-08-19'),
  ('SMC048', 'COLOR GEL AMARILLOS SEMI', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 1, 0, '2025-08-19'),
  ('HS03', 'COLOR GEL AMARILLOS SEMI', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 0, 0, '2025-08-19'),
  ('153 PASTEL YELLOW', 'COLOR GEL AMARILLOS SEMI', 'Esmaltero semipermanente', 'ORGANIC', 'unidad', 1, 0, '2025-08-19'),
  ('028 SAILOR SUN', 'COLOR GEL AMARILLOS SEMI', 'Esmaltero semipermanente', 'ORGANIC', 'unidad', 2, 0, '2025-08-19'),
  ('HIPERACTIVA', 'COLOR GEL AMARILLOS SEMI', 'Esmaltero semipermanente', 'MASGLO', 'unidad', 1, 0, '2025-08-19'),
  ('SC 119', 'COLOR GEL NARANJA SEMI', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 0, 0, '2025-08-19'),
  ('SMC039', 'COLOR GEL NARANJA SEMI', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 1, 0, '2025-08-19'),
  ('SMC040', 'COLOR GEL NARANJA SEMI', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 1, 0, '2025-08-19'),
  ('13', 'COLOR GEL NARANJA SEMI', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 1, 0, '2025-08-19'),
  ('SMC 082', 'COLOR GEL NARANJA SEMI', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 1, 0, '2025-08-19'),
  ('156 PASTEL PEACH', 'COLOR GEL NARANJA SEMI', 'Esmaltero semipermanente', 'ORGANIC', 'unidad', 1, 0, '2025-08-19'),
  ('046 IMPERIAL ORANGE', 'COLOR GEL NARANJA SEMI', 'Esmaltero semipermanente', 'ORGANIC', 'unidad', 1, 0, '2025-08-19'),
  ('NEON ORANGE', 'COLOR GEL NEON SEMI', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 1, 0, '2025-08-19'),
  ('NEON GREEN', 'COLOR GEL NEON SEMI', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 1, 0, '2025-08-19'),
  ('NEON YELLOW', 'COLOR GEL NEON SEMI', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 1, 0, '2025-08-19'),
  ('NEON BLUE', 'COLOR GEL NEON SEMI', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 1, 0, '2025-08-19'),
  ('NEON RED', 'COLOR GEL NEON SEMI', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 1, 0, '2025-08-19'),
  ('063 GLOW ORANGE', 'COLOR GEL NEON SEMI', 'Esmaltero semipermanente', 'ORGANIC', 'unidad', 1, 0, '2025-08-19'),
  ('064 GLOW GREEN', 'COLOR GEL NEON SEMI', 'Esmaltero semipermanente', 'ORGANIC', 'unidad', 1, 0, '2025-08-19'),
  ('065 GLOW BLUE', 'COLOR GEL NEON SEMI', 'Esmaltero semipermanente', 'ORGANIC', 'unidad', 1, 0, '2025-08-19'),
  ('062 GLUE YELLOW', 'COLOR GEL NEON SEMI', 'Esmaltero semipermanente', 'ORGANIC', 'unidad', 1, 0, '2025-08-19'),
  ('067 GLOW PINK', 'COLOR GEL NEON SEMI', 'Esmaltero semipermanente', 'ORGANIC', 'unidad', 1, 0, '2025-08-19'),
  ('196', 'COLOR GEL FNAILS', 'Esmaltero semipermanente', 'FNAILS', 'unidad', 1, 0, '2025-08-19'),
  ('77', 'COLOR GEL FNAILS', 'Esmaltero semipermanente', 'FNAILS', 'unidad', 1, 0, '2025-08-19'),
  ('2', 'COLOR GEL FNAILS', 'Esmaltero semipermanente', 'FNAILS', 'unidad', 1, 0, '2025-08-19'),
  ('43', 'COLOR GEL FNAILS', 'Esmaltero semipermanente', 'FNAILS', 'unidad', 1, 0, '2025-08-19'),
  ('50', 'COLOR GEL FNAILS', 'Esmaltero semipermanente', 'FNAILS', 'unidad', 1, 0, '2025-08-19'),
  ('154', 'COLOR GEL FNAILS', 'Esmaltero semipermanente', 'FNAILS', 'unidad', 1, 0, '2025-08-19'),
  ('132', 'COLOR GEL FNAILS', 'Esmaltero semipermanente', 'FNAILS', 'unidad', 1, 0, '2025-08-19'),
  ('166', 'COLOR GEL FNAILS', 'Esmaltero semipermanente', 'FNAILS', 'unidad', 1, 0, '2025-08-19'),
  ('65', 'COLOR GEL FNAILS', 'Esmaltero semipermanente', 'FNAILS', 'unidad', 1, 0, '2025-08-19'),
  ('64', 'COLOR GEL FNAILS', 'Esmaltero semipermanente', 'FNAILS', 'unidad', 1, 0, '2025-08-19'),
  ('58', 'COLOR GEL FNAILS', 'Esmaltero semipermanente', 'FNAILS', 'unidad', 1, 0, '2025-08-19'),
  ('138', 'COLOR GEL FNAILS', 'Esmaltero semipermanente', 'FNAILS', 'unidad', 1, 0, '2025-08-19'),
  ('TEMPCREAM 085', 'COLOR GEL TERMICOS', 'Esmaltero semipermanente', 'ORGANIC', 'unidad', 1, 0, '2025-08-19'),
  ('TEMP ROSA', 'COLOR GEL TERMICOS', 'Esmaltero semipermanente', 'ORGANIC', 'unidad', 1, 0, '2025-08-19'),
  ('TEMP GRAY 088', 'COLOR GEL TERMICOS', 'Esmaltero semipermanente', 'ORGANIC', 'unidad', 1, 0, '2025-08-19'),
  ('TEMP LAVANDA 087', 'COLOR GEL TERMICOS', 'Esmaltero semipermanente', 'ORGANIC', 'unidad', 1, 0, '2025-08-19'),
  ('TEMP MAGENTA 090', 'COLOR GEL TERMICOS', 'Esmaltero semipermanente', 'ORGANIC', 'unidad', 1, 0, '2025-08-19'),
  ('TEMP WINE 083', 'COLOR GEL TERMICOS', 'Esmaltero semipermanente', 'ORGANIC', 'unidad', 1, 0, '2025-08-19'),
  ('TEMP COBALT 086', 'COLOR GEL TERMICOS', 'Esmaltero semipermanente', 'ORGANIC', 'unidad', 1, 0, '2025-08-19'),
  ('145 CRYSTAL ORANGE', 'COLOR GEL CRISTAL', 'Esmaltero semipermanente', 'ORGANIC', 'unidad', 2, 0, '2025-08-19'),
  ('147 CRYSTAL YELLOW', 'COLOR GEL CRISTAL', 'Esmaltero semipermanente', 'ORGANIC', 'unidad', 1, 0, '2025-08-19'),
  ('141 CRYSTAL PURPLE', 'COLOR GEL CRISTAL', 'Esmaltero semipermanente', 'ORGANIC', 'unidad', 1, 0, '2025-08-19'),
  ('146 CRYSTAL RED', 'COLOR GEL CRISTAL', 'Esmaltero semipermanente', 'ORGANIC', 'unidad', 1, 0, '2025-08-19'),
  ('142 CRYSTAL BLUE', 'COLOR GEL CRISTAL', 'Esmaltero semipermanente', 'ORGANIC', 'unidad', 1, 0, '2025-08-19'),
  ('GLASS GEL 001', 'COLOR GEL CRISTAL', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 1, 0, '2026-02-03'),
  ('GLASS GEL 009', 'COLOR GEL CRISTAL', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 1, 0, '2026-02-03'),
  ('9', 'COLOR GEL FLASH', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 0, 0, '2025-08-19'),
  ('16', 'COLOR GEL FLASH', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 2, 0, '2025-08-19'),
  ('14', 'COLOR GEL FLASH', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 1, 0, '2025-08-19'),
  ('13', 'COLOR GEL FLASH', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 1, 0, '2025-08-19'),
  ('18', 'COLOR GEL FLASH', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 1, 0, '2025-08-19'),
  ('15', 'COLOR GEL FLASH', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 1, 0, '2025-08-19'),
  ('12', 'COLOR GEL FLASH', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 1, 0, '2025-08-19'),
  ('17', 'COLOR GEL FLASH', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 1, 0, '2025-08-19'),
  ('069 FAIRY WHITE', 'COLOR GEL ESCARCHADO', 'Esmaltero semipermanente', 'ORGANIC', 'unidad', 1, 0, '2025-08-20'),
  ('072 FAIRY ESMERALD', 'COLOR GEL ESCARCHADO', 'Esmaltero semipermanente', 'ORGANIC', 'unidad', 1, 0, '2025-08-20'),
  ('074 FAIRY LILAC', 'COLOR GEL ESCARCHADO', 'Esmaltero semipermanente', 'ORGANIC', 'unidad', 1, 0, '2025-08-20'),
  ('096 LOVE SPELL', 'COLOR GEL ESCARCHADO', 'Esmaltero semipermanente', 'ORGANIC', 'unidad', 2, 0, '2025-08-20'),
  ('3 ROJO', 'COLOR GEL ESCARCHADO', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 1, 0, '2025-08-20'),
  ('14 ROJO', 'COLOR GEL ESCARCHADO', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 1, 0, '2025-08-20'),
  ('JH11', 'COLOR GEL ESCARCHADO', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 1, 0, '2025-08-20'),
  ('W 10', 'COLOR GEL ESCARCHADO', 'Esmaltero semipermanente', 'ROSALIND', 'unidad', 1, 0, '2025-08-20'),
  ('WG08', 'COLOR GEL ESCARCHADO', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 2, 0, '2025-08-20'),
  ('1864', 'COLOR GEL ESCARCHADO', 'Esmaltero semipermanente', 'ROSALIND', 'unidad', 1, 0, '2025-08-20'),
  ('25 ROSADO', 'COLOR GEL ESCARCHADO', 'Esmaltero semipermanente', 'CANNI', 'unidad', 1, 0, '2025-08-20'),
  ('5 ROSADO', 'COLOR GEL ESCARCHADO', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 1, 0, '2025-08-20'),
  ('MORADO', 'COLOR GEL ESCARCHADO', 'Esmaltero semipermanente', 'CANNI', 'unidad', 1, 0, '2025-08-20'),
  ('19 LILA', 'COLOR GEL ESCARCHADO', 'Esmaltero semipermanente', 'CANNI', 'unidad', 1, 0, '2025-08-20'),
  ('LB12', 'COLOR GEL ESCARCHADO', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 1, 0, '2025-08-20'),
  ('BJ03', 'COLOR GEL ESCARCHADO', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 1, 0, '2026-02-03'),
  ('WG03', 'COLOR GEL ESCARCHADO', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 1, 0, '2026-02-03'),
  ('BJ 02', 'COLOR GEL ESCARCHADO', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 1, 0, '2025-08-20'),
  ('AZUL', 'COLOR GEL ESCARCHADO', 'Esmaltero semipermanente', 'CANNI', 'unidad', 1, 0, '2025-08-20'),
  ('JT11', 'COLOR GEL ESCARCHADO', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 1, 0, '2025-08-20'),
  ('5 ROSADO', 'COLOR GEL ESCARCHADO', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 1, 0, '2025-08-20'),
  ('BJ01', 'COLOR GEL ESCARCHADO', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 3, 0, '2025-08-20'),
  ('BJ02', 'COLOR GEL ESCARCHADO', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 1, 0, '2025-08-20'),
  ('JH10', 'COLOR GEL ESCARCHADO', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 1, 0, '2025-08-20'),
  ('JY10', 'COLOR GEL ESCARCHADO', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 1, 0, '2025-08-20'),
  ('BLUE HAWAII', 'COLOR GEL ESCARCHADO', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 1, 0, '2025-08-20'),
  ('PINK STARBURST', 'COLOR GEL ESCARCHADO', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 1, 0, '2025-08-20'),
  ('WHITE COSMOPOLITAN', 'COLOR GEL ESCARCHADO', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 1, 0, '2026-02-03'),
  ('ESPEJO PLATEADO', 'COLOR GEL EFECTO', 'Esmaltero semipermanente', 'XEIJAY', 'unidad', 2, 0, NULL),
  ('LIQUIDO POLYGEL', 'ARTIFICIAL', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 1, 0, '2025-08-20'),
  ('06 POLYGEL 30ML', 'ARTIFICIAL', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 4, 0, '2025-08-20'),
  ('POLYGEL 60ML', 'ARTIFICIAL', 'Esmaltero semipermanente', 'MIXCOCO', 'unidad', 2, 0, '2025-08-20'),
  ('GRANDE', 'CHOCOLATERAPIA', 'Esmaltero semipermanente', NULL, 'unidad', 1, 0, '2025-08-20'),
  ('PEQUEÑO', 'CHOCOLATERAPIA', 'Esmaltero semipermanente', 'RT', 'unidad', 1, 0, '2025-08-20'),
  ('12 ROJO', 'OJO DE GATO', 'Esmaltero gato y painting', 'MIXCOCO', 'unidad', 0, 0, '2025-08-20'),
  ('33 MOONLIGTH', 'OJO DE GATO', 'Esmaltero gato y painting', 'MIXCOCO', 'unidad', 1, 0, '2025-08-20'),
  ('9D 06', 'OJO DE GATO', 'Esmaltero gato y painting', 'MIXCOCO', 'unidad', 1, 0, '2025-08-20'),
  ('09 MOONLIGTH', 'OJO DE GATO', 'Esmaltero gato y painting', 'MIXCOCO', 'unidad', 2, 0, '2025-08-20'),
  ('3 AZUL', 'OJO DE GATO', 'Esmaltero gato y painting', 'MIXCOCO', 'unidad', 1, 0, '2025-08-20'),
  ('CAZADORA', 'OJO DE GATO', 'Esmaltero gato y painting', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('D22', 'OJO DE GATO', 'Esmaltero gato y painting', 'TEMU', 'unidad', 1, 0, '2025-08-20'),
  ('D23', 'OJO DE GATO', 'Esmaltero gato y painting', 'TEMU', 'unidad', 1, 0, '2025-08-20'),
  ('D24', 'OJO DE GATO', 'Esmaltero gato y painting', 'TEMU', 'unidad', 1, 0, '2025-08-20'),
  ('D25', 'OJO DE GATO', 'Esmaltero gato y painting', 'TEMU', 'unidad', 1, 0, '2025-08-20'),
  ('D26', 'OJO DE GATO', 'Esmaltero gato y painting', 'TEMU', 'unidad', 1, 0, '2025-08-20'),
  ('D27', 'OJO DE GATO', 'Esmaltero gato y painting', 'TEMU', 'unidad', 1, 0, '2025-08-20'),
  ('NARANJA', 'OJO DE GATO', 'Esmaltero gato y painting', 'SENGCOU', 'unidad', 1, 0, '2025-08-20'),
  ('AMARILLO', 'OJO DE GATO', 'Esmaltero gato y painting', 'SENGCOU', 'unidad', 1, 0, '2025-08-20'),
  ('138 VIOLET', 'OJO DE GATO', 'Esmaltero gato y painting', 'ORGANIC', 'unidad', 1, 0, '2025-08-20'),
  ('134 AQUA', 'OJO DE GATO', 'Esmaltero gato y painting', 'ORGANIC', 'unidad', 1, 0, '2025-08-20'),
  ('#10', 'OJO DE GATO', 'Esmaltero gato y painting', 'XEIJAYI', 'unidad', 0, 0, '2025-08-20'),
  ('03 DIAMANTE', 'OJO DE GATO', 'Esmaltero gato y painting', 'CHARLOTTE', 'unidad', 1, 0, '2025-08-20'),
  ('PRIMITIVA', 'OJO DE GATO', 'Esmaltero gato y painting', 'MASGLO', 'unidad', 1, 0, '2026-02-02'),
  ('PLATEADO', 'OJO DE GATO', 'Esmaltero gato y painting', 'MIXCOCO', 'unidad', 1, 0, '2026-02-02'),
  ('LILA', 'OJO DE GATO', 'Esmaltero gato y painting', 'MIXCOCO', 'unidad', 1, 0, '2026-02-02'),
  ('GOLDEN 01', 'OJO DE GATO', 'Esmaltero gato y painting', 'MIXCOCO', 'unidad', 1, 0, '2026-02-02'),
  ('PRINCESS 05', 'OJO DE GATO', 'Esmaltero gato y painting', 'MIXCOCO', 'unidad', 1, 0, '2026-02-02'),
  ('PLATA', 'OJO DE GATO', 'Esmaltero gato y painting', 'XEIJAYI', 'unidad', 1, 0, '2026-02-02'),
  ('ROSA', 'OJO DE GATO', 'Esmaltero gato y painting', 'XEIJAYI', 'unidad', 1, 0, '2026-02-02'),
  ('O2', 'OJO DE GATO', 'Esmaltero gato y painting', 'XEIJAYI', 'unidad', 0, 0, '2026-02-02'),
  ('GEL', 'GEL SOLIDO', 'Esmaltero gato y painting', 'RONIKI', 'unidad', 1, 0, '2025-08-20'),
  ('GEL', 'GEL SOLIDO', 'Esmaltero gato y painting', 'ANTONELLA', 'unidad', 2, 0, '2025-08-20'),
  ('GEL', 'GEL SOLIDO', 'Esmaltero gato y painting', 'FULLBEAUTY', 'unidad', 2, 0, '2025-08-20'),
  ('GEL', 'GEL SOLIDO', 'Esmaltero gato y painting', 'JIACHICO', 'unidad', 2, 0, '2025-08-20'),
  ('COVER NATURAL', 'ACRILICO', 'Esmaltero gato y painting', 'ORGANIC', 'unidad', 1, 0, '2025-08-20'),
  ('PETAL', 'ACRILICO', 'Esmaltero gato y painting', 'ORGANIC', 'unidad', 2, 0, '2025-08-20'),
  ('CREAMY WHITE', 'ACRILICO', 'Esmaltero gato y painting', 'ORGANIC', 'unidad', 1, 0, '2025-08-20'),
  ('CRYSTAL CLEAR', 'ACRILICO', 'Esmaltero gato y painting', 'ORGANIC', 'unidad', 1, 0, '2025-08-20'),
  ('COVER', 'ACRILICO', 'Esmaltero gato y painting', 'MIXCOCO', 'unidad', 1, 0, '2026-02-02'),
  ('NUDE', 'BUIDER', 'Esmaltero gato y painting', 'MIXCOCO', 'unidad', 1, 0, '2026-02-02'),
  ('DORADO', 'PAINTING GEL', 'Esmaltero gato y painting', 'QUEENIGTH', 'unidad', 1, 0, '2025-08-20'),
  ('DORADO 004', 'PAINTING GEL', 'Esmaltero gato y painting', 'TEMU', 'unidad', 1, 0, '2025-08-20'),
  ('DORADO 12', 'PAINTING GEL', 'Esmaltero gato y painting', 'M&Y', 'unidad', 1, 0, '2025-08-20'),
  ('MATALIC GOLDEN', 'PAINTING GEL', 'Esmaltero gato y painting', 'TEMU', 'unidad', 1, 0, '2025-08-20'),
  ('GOLD', 'PAINTING GEL', 'Esmaltero gato y painting', 'MIXCOCO', 'unidad', 1, 0, '2025-08-20'),
  ('OO3', 'PAINTING GEL', 'Esmaltero gato y painting', 'TEMU', 'unidad', 1, 0, '2025-08-20'),
  ('SILVER', 'PAINTING GEL', 'Esmaltero gato y painting', 'MIXCOCO', 'unidad', 2, 0, '2025-08-20'),
  ('ROSE GOLD', 'PAINTING GEL', 'Esmaltero gato y painting', 'MIXCOCO', 'unidad', 1, 0, '2025-08-20'),
  ('NEGRO', 'ELASTIC', 'Esmaltero gato y painting', 'MIXCOCO', 'unidad', 1, 0, '2025-08-20'),
  ('BLANCO', 'ELASTIC', 'Esmaltero gato y painting', 'MIXCOCO', 'unidad', 1, 0, '2025-08-20'),
  ('No 2', 'PLATINUM', 'Esmaltero gato y painting', 'MIXCOCO', 'unidad', 1, 0, '2025-08-20'),
  ('No 6', 'PLATINUM', 'Esmaltero gato y painting', 'MIXCOCO', 'unidad', 1, 0, '2025-08-20'),
  ('No 8', 'PLATINUM', 'Esmaltero gato y painting', 'MIXCOCO', 'unidad', 1, 0, '2025-08-20'),
  ('No 11', 'PLATINUM', 'Esmaltero gato y painting', 'MIXCOCO', 'unidad', 1, 0, '2025-08-20'),
  ('BJ 07', 'PAINTING ESCARCHADO', 'Esmaltero gato y painting', 'MIXCOCO', 'unidad', 1, 0, '2025-08-20'),
  ('BJ 03', 'PAINTING ESCARCHADO', 'Esmaltero gato y painting', 'MIXCOCO', 'unidad', 1, 0, '2025-08-20'),
  ('BJ 01', 'PAINTING ESCARCHADO', 'Esmaltero gato y painting', 'MIXCOCO', 'unidad', 1, 0, '2025-08-20'),
  ('BJ 02', 'PAINTING ESCARCHADO', 'Esmaltero gato y painting', 'MIXCOCO', 'unidad', 1, 0, '2025-08-20'),
  ('X 02', 'PAINTING GEL', 'Esmaltero gato y painting', 'MIXCOCO', 'unidad', 1, 0, '2025-08-20'),
  ('X 03', 'PAINTING GEL', 'Esmaltero gato y painting', 'MIXCOCO', 'unidad', 1, 0, '2025-08-20'),
  ('SC 1165', 'PAINTING GEL', 'Esmaltero gato y painting', 'MIXCOCO', 'unidad', 1, 0, '2025-08-20'),
  ('LF 01', 'PAINTING GEL', 'Esmaltero gato y painting', 'MIXCOCO', 'unidad', 1, 0, '2025-08-20'),
  ('SC 879', 'PAINTING GEL', 'Esmaltero gato y painting', 'MIXCOCO', 'unidad', 1, 0, '2025-08-20'),
  ('PINK 005', 'PAINTING GEL', 'Esmaltero gato y painting', 'MIRACLE', 'unidad', 1, 0, '2025-08-20'),
  ('ZZ 02', 'PAINTING GEL', 'Esmaltero gato y painting', 'MIXCOCO', 'unidad', 1, 0, '2025-08-20'),
  ('ZS 05', 'PAINTING GEL', 'Esmaltero gato y painting', 'MIXCOCO', 'unidad', 1, 0, '2025-08-20'),
  ('JT 01', 'PAINTING GEL', 'Esmaltero gato y painting', 'MIXCOCO', 'unidad', 2, 0, '2025-08-20'),
  ('JT 03', 'PAINTING GEL', 'Esmaltero gato y painting', 'MIXCOCO', 'unidad', 1, 0, '2025-08-20'),
  ('JT 05', 'PAINTING GEL', 'Esmaltero gato y painting', 'MIXCOCO', 'unidad', 1, 0, '2025-08-20'),
  ('SC 195', 'PAINTING GEL', 'Esmaltero gato y painting', 'MIXCOCO', 'unidad', 1, 0, '2025-08-20'),
  ('LS 08', 'PAINTING GEL', 'Esmaltero gato y painting', 'MIXCOCO', 'unidad', 2, 0, '2025-08-20'),
  ('SMC 061', 'PAINTING GEL', 'Esmaltero gato y painting', 'MIXCOCO', 'unidad', 1, 0, '2025-08-20'),
  ('HS 03', 'PAINTING GEL', 'Esmaltero gato y painting', 'MIXCOCO', 'unidad', 1, 0, '2025-08-20'),
  ('HS 02', 'PAINTING GEL', 'Esmaltero gato y painting', 'MIXCOCO', 'unidad', 1, 0, '2025-08-20'),
  ('DMC 493', 'PAINTING GEL', 'Esmaltero gato y painting', 'MIXCOCO', 'unidad', 1, 0, '2025-08-20'),
  ('SMC 008', 'PAINTING GEL', 'Esmaltero gato y painting', 'MIXCOCO', 'unidad', 1, 0, '2025-08-20'),
  ('QQ 09', 'PAINTING GEL', 'Esmaltero gato y painting', 'MIXCOCO', 'unidad', 1, 0, '2025-08-20'),
  ('QQ 02', 'PAINTING GEL', 'Esmaltero gato y painting', 'MIXCOCO', 'unidad', 1, 0, '2025-08-20'),
  ('QQ 04', 'PAINTING GEL', 'Esmaltero gato y painting', 'MIXCOCO', 'unidad', 1, 0, '2025-08-20'),
  ('BLANCO', 'PAINTING GEL', 'Esmaltero gato y painting', 'ORGANIC', 'unidad', 2, 0, '2025-08-20'),
  ('NEGRO', 'PAINTING GEL', 'Esmaltero gato y painting', 'ORGANIC', 'unidad', 1, 0, '2025-08-20'),
  ('BLANCO', 'PAINTING GEL', 'Esmaltero gato y painting', 'MIXCOCO', 'unidad', 1, 0, '2025-08-20'),
  ('NEGRO', 'PAINTING GEL', 'Esmaltero gato y painting', 'MIXCOCO', 'unidad', 1, 0, '2025-08-20'),
  ('BLANCO', 'PAINTING GEL', 'Esmaltero gato y painting', 'TEMU', 'unidad', 1, 0, '2025-08-20'),
  ('NEGRO', 'PAINTING GEL', 'Esmaltero gato y painting', 'TEMU', 'unidad', 1, 0, '2025-08-20'),
  ('REFINADA', 'SECADO RAPIDO ESCARCHADO', 'Esmaltero secado rápido', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('LIBRE', 'SECADO RAPIDO ESCARCHADO', 'Esmaltero secado rápido', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('TALENTOSA', 'SECADO RAPIDO ESCARCHADO', 'Esmaltero secado rápido', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('BRILLO GALACTICO', 'SECADO RAPIDO ESCARCHADO', 'Esmaltero secado rápido', 'MASGLO', 'unidad', 3, 0, '2025-08-20'),
  ('GRANIZADO DORADO', 'SECADO RAPIDO ESCARCHADO', 'Esmaltero secado rápido', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('BRILLO CORAL', 'SECADO RAPIDO ESCARCHADO', 'Esmaltero secado rápido', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('QUISQUILLOSA', 'SECADO RAPIDO ESCARCHADO', 'Esmaltero secado rápido', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('REGIA', 'SECADO RAPIDO ESCARCHADO', 'Esmaltero secado rápido', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('SOÑADORA', 'SECADO RAPIDO ESCARCHADO', 'Esmaltero secado rápido', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('FRANCES', 'SECADO RAPIDO TRASLUCIDO', 'Esmaltero secado rápido', 'MASGLO', 'unidad', 2, 0, '2025-08-20'),
  ('NOVIA', 'SECADO RAPIDO TRASLUCIDO', 'Esmaltero secado rápido', 'MASGLO', 'unidad', 2, 0, '2025-08-20'),
  ('BELLA', 'SECADO RAPIDO TRASLUCIDO', 'Esmaltero secado rápido', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('REBELDE', 'SECADO RAPIDO TRASLUCIDO', 'Esmaltero secado rápido', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('EJECUTIVA', 'SECADO RAPIDO TRASLUCIDO', 'Esmaltero secado rápido', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('BLANCO', 'SECADO RAPIDO COLOR GEL', 'Esmaltero secado rápido', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('NEGRO', 'SECADO RAPIDO COLOR GEL', 'Esmaltero secado rápido', 'MASGLO', 'unidad', 2, 0, '2025-08-20'),
  ('TESCENDENTAL', 'SECADO RAPIDO COLOR GEL', 'Esmaltero secado rápido', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('BUSCONA', 'SECADO RAPIDO COLOR GEL', 'Esmaltero secado rápido', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('ACTIVISTA', 'SECADO RAPIDO COLOR GEL', 'Esmaltero secado rápido', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('TRANQUILA', 'SECADO RAPIDO COLOR GEL', 'Esmaltero secado rápido', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('AMBIANTALISTA', 'SECADO RAPIDO COLOR GEL', 'Esmaltero secado rápido', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('AUTENTICA', 'SECADO RAPIDO COLOR GEL', 'Esmaltero secado rápido', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('COOL', 'SECADO RAPIDO COLOR GEL', 'Esmaltero secado rápido', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('TIMIDA', 'SECADO RAPIDO COLOR GEL', 'Esmaltero secado rápido', 'MASGLO', 'unidad', 2, 0, '2025-08-20'),
  ('SOLTERA', 'SECADO RAPIDO COLOR GEL', 'Esmaltero secado rápido', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('BONDADOSA', 'SECADO RAPIDO COLOR GEL', 'Esmaltero secado rápido', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('DINAMICA', 'SECADO RAPIDO COLOR GEL', 'Esmaltero secado rápido', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('PIONERA', 'SECADO RAPIDO COLOR GEL', 'Esmaltero secado rápido', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('ENCANTADORA', 'SECADO RAPIDO COLOR GEL', 'Esmaltero secado rápido', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('NATIVA', 'SECADO RAPIDO COLOR GEL', 'Esmaltero secado rápido', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('RADIANTE', 'SECADO RAPIDO COLOR GEL', 'Esmaltero secado rápido', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('MATRIMONIO', 'SECADO RAPIDO COLOR GEL', 'Esmaltero secado rápido', 'MASGLO', 'unidad', 2, 0, '2025-08-20'),
  ('COMPULSIVA', 'SECADO RAPIDO COLOR GEL', 'Esmaltero secado rápido', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('PRIMERA DAMA', 'SECADO RAPIDO COLOR GEL', 'Esmaltero secado rápido', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('DIVA', 'SECADO RAPIDO COLOR GEL', 'Esmaltero secado rápido', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('HUMANA', 'SECADO RAPIDO COLOR GEL', 'Esmaltero secado rápido', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('EXPRESIVA', 'SECADO RAPIDO COLOR GEL', 'Esmaltero secado rápido', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('INTUITIVA', 'SECADO RAPIDO COLOR GEL', 'Esmaltero secado rápido', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('BOMBOM', 'SECADO RAPIDO COLOR GEL', 'Esmaltero secado rápido', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('JUGUETONA', 'SECADO RAPIDO COLOR GEL', 'Esmaltero secado rápido', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('COMICA', 'SECADO RAPIDO COLOR GEL', 'Esmaltero secado rápido', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('RISUEÑA', 'SECADO RAPIDO COLOR GEL', 'Esmaltero secado rápido', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('DISTINGUIDA', 'SECADO RAPIDO COLOR GEL', 'Esmaltero secado rápido', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('LINDA', 'SECADO RAPIDO COLOR GEL', 'Esmaltero secado rápido', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('AUSENTE', 'SECADO RAPIDO COLOR GEL', 'Esmaltero secado rápido', 'MASGLO', 'unidad', 2, 0, '2025-08-20'),
  ('INSINUANTE', 'SECADO RAPIDO COLOR GEL', 'Esmaltero secado rápido', 'MASGLO', 'unidad', 2, 0, '2025-08-20'),
  ('REVOLUCIONARIA', 'SECADO RAPIDO COLOR GEL', 'Esmaltero secado rápido', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('QUERENDONA', 'SECADO RAPIDO COLOR GEL', 'Esmaltero secado rápido', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('SANGRE TORO', 'SECADO RAPIDO COLOR GEL', 'Esmaltero secado rápido', 'MASGLO', 'unidad', 2, 0, '2025-08-20'),
  ('SOFISTICADA', 'SECADO RAPIDO COLOR GEL', 'Esmaltero secado rápido', 'MASGLO', 'unidad', 1, 0, '2026-02-21'),
  ('VISIONARIA', 'SECADO RAPIDO COLOR GEL', 'Esmaltero secado rápido', 'MASGLO', 'unidad', 2, 0, '2026-02-21'),
  ('GOLOSO', 'SECADO RAPIDO COLOR GEL', 'Esmaltero secado rápido', 'MASGLO', 'unidad', 1, 0, '2026-02-21'),
  ('BASE', 'SECADO RAPIDO', 'Esmaltero secado rápido', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('BRILLO', 'SECADO RAPIDO', 'Esmaltero secado rápido', 'MASGLO', 'unidad', 0, 0, '2025-08-20'),
  ('BASE NUTRITIVA', 'SECADO RAPIDO', 'Esmaltero secado rápido', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('MATIFICANTE', 'SECADO RAPIDO', 'Esmaltero secado rápido', 'MASGLO', 'unidad', 4, 0, '2025-08-20'),
  ('CLINICAL', 'SECADO RAPIDO', 'Esmaltero secado rápido', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('LYCHEE FT T', 'SECADO RAPIDO', 'Esmaltero secado rápido', 'DUNIVERSE', 'unidad', 1, 0, '2025-08-20'),
  ('LYCHEE AZUL', 'SECADO RAPIDO', 'Esmaltero secado rápido', 'DUNIVERSE', 'unidad', 1, 0, '2025-08-20'),
  ('NEBULA', 'SECADO RAPIDO', 'Esmaltero secado rápido', 'DUNIVERSE', 'unidad', 1, 0, '2025-08-20'),
  ('SERENATA', 'SECADO RAPIDO', 'Esmaltero secado rápido', 'DUNIVERSE', 'unidad', 1, 0, '2025-08-20'),
  ('DESTELLO', 'SECADO RAPIDO', 'Esmaltero secado rápido', 'DUNIVERSE', 'unidad', 1, 0, '2025-08-20'),
  ('SIDERAL', 'SECADO RAPIDO', 'Esmaltero secado rápido', 'DUNIVERSE', 'unidad', 1, 0, '2025-08-20'),
  ('CORAL', 'TRADICIONAL ESCARCHADO', 'Esmaltero tradicional', 'MASGLO', 'unidad', 2, 0, '2025-08-20'),
  ('BRILLO CONFIANZA', 'TRADICIONAL ESCARCHADO', 'Esmaltero tradicional', 'MASGLO', 'unidad', 2, 0, '2025-08-20'),
  ('BRILLO TRES OROS', 'TRADICIONAL ESCARCHADO', 'Esmaltero tradicional', 'MASGLO', 'unidad', 2, 0, '2025-08-20'),
  ('BRILLO BENEVOLENTE', 'TRADICIONAL ESCARCHADO', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('BRILLO DESTELLOS', 'TRADICIONAL ESCARCHADO', 'Esmaltero tradicional', 'MASGLO', 'unidad', 0, 0, '2025-08-20'),
  ('ORGINAL', 'TRADICIONAL ESCARCHADO', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('GITANA', 'TRADICIONAL ESCARCHADO', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('QUISQUILLOSA', 'TRADICIONAL ESCARCHADO', 'Esmaltero tradicional', 'MASGLO', 'unidad', 2, 0, '2025-08-20'),
  ('REGIA', 'TRADICIONAL ESCARCHADO', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('BRILLO ARCOIRIS', 'TRADICIONAL ESCARCHADO', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('GRANIZADO DORADO', 'TRADICIONAL ESCARCHADO', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('ESCARCHADO DORADO', 'TRADICIONAL ESCARCHADO', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('ESCARCHADO PLATA', 'TRADICIONAL ESCARCHADO', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('NOVIA', 'TRADICIONAL TRASLUCIDO', 'Esmaltero tradicional', 'MASGLO', 'unidad', 2, 0, '2025-08-20'),
  ('BELLA', 'TRADICIONAL TRASLUCIDO', 'Esmaltero tradicional', 'MASGLO', 'unidad', 3, 0, '2025-08-20'),
  ('FRANCES', 'TRADICIONAL TRASLUCIDO', 'Esmaltero tradicional', 'MASGLO', 'unidad', 2, 0, '2025-08-20'),
  ('REBELDE', 'TRADICIONAL TRASLUCIDO', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('EJECUTIVA', 'TRADICIONAL TRASLUCIDO', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('NATURAL', 'TRADICIONAL TRASLUCIDO', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('NIEVE', 'TRADICIONAL TRASLUCIDO', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('CALMADA', 'TRADICIONAL TRASLUCIDO', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('BLANCO', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 4, 0, '2025-08-20'),
  ('NEGRO', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 5, 0, '2025-08-20'),
  ('BAILADORA', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('ARTESANA', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('BUSCONA', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('ZANGANA', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('ELECTRICA', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2026-02-02'),
  ('EMPRENDEDORA', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 2, 0, '2025-08-20'),
  ('CHIC', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('PASIONAL', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('EXPERIMENTADA', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('FAMOSA', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('OSTENTOSA', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('EDUCADA', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('BLANCO NACAR', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('GITANA', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('ORIGINAL', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('BRILLO SEDA', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('FUFURUFA', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('LINDA', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('FIESTA', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('LUJURIOSA', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('MAGICA', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('MALVADA', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('INSINUANTE', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('AUSENTE', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('GOLOSA', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('SANGRE TORO', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 2, 0, '2025-08-20'),
  ('GOMELA', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('INSPIRADORA', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('MORRONGA', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('ADORABLE', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('ACTIVISTA', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('ABRUMADORA', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('LUCHADORA', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('ENTRETENIDA', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('CONSIENTE', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('SOLIDARIA', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 2, 0, '2025-08-20'),
  ('CONTROLADORA', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('TRANQUILA', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 2, 0, '2025-08-20'),
  ('MARINERA', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('CASQUIVANA', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('SALVAJE', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('AZUL REY', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('INQUIETA', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('EXAGERADA', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('TIERNA', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('ATREVIDA', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('MIMADA', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 2, 0, '2025-08-20'),
  ('DOMINANTE', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('SOFISTICADA', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('MATRIMONIO', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 2, 0, '2025-08-20'),
  ('PRIMERA DAMA', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('EXPRESIVA', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('NATIVA', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('MATERIALISTA', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('RECATADA', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('ILUSION', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 2, 0, '2025-08-20'),
  ('JUGUETONA', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('CANDIDATA', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('PERFECCIONISTA', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('BIPOLAR', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('COMICA', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('RAZONABLE', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('VIRGINAL', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('DOBLE', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('SOLTERA', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 2, 0, '2025-08-20'),
  ('AMANTE', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('TOXICA', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('IMPONENTE', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('CONSENTIDA', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('VANGUARDISTA', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('QUERENDONA', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 2, 0, '2025-08-20'),
  ('RELEJADA', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('FABULOSA', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('TIRANA', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('TRACENDENTAL', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('METODICA', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, NULL),
  ('BRILLO', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 2, 0, '2025-08-20'),
  ('MATIFICANTE', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('MATTE HOMBRE', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 1, 0, '2025-08-20'),
  ('BRILLO HOMBRE', 'TRADICIONAL ESMALTE', 'Esmaltero tradicional', 'MASGLO', 'unidad', 2, 0, '2025-08-20'),
  ('CONTROLADORA', 'TRADICIONAL', 'Recepción', 'MASGLO', 'unidad', 1, 0, NULL),
  ('NOVIA', 'TRADICIONAL', 'Recepción', 'MASGLO', 'unidad', 1, 0, NULL),
  ('TIZA', 'TRADICIONAL', 'Recepción', 'MASGLO', 'unidad', 2, 0, NULL),
  ('BASE', 'TRADICIONAL', 'Recepción', 'MASGLO', 'unidad', 4, 0, NULL),
  ('EXPRESIVA', 'SECADO RAPIDO', 'Recepción', 'MASGLO', 'unidad', 1, 0, NULL),
  ('INSINUANTE', 'SECADO RAPIDO', 'Recepción', 'MASGLO', 'unidad', 1, 0, NULL),
  ('LIBRE', 'SECADO RAPIDO', 'Recepción', 'MASGLO', 'unidad', 1, 0, NULL),
  ('TIZA', 'SECADO RAPIDO', 'Recepción', 'MASGLO', 'unidad', 3, 0, NULL),
  ('BASE', 'SECADO RAPIDO', 'Recepción', 'MASGLO', 'unidad', 3, 0, NULL),
  ('BRILLO', 'SECADO RAPIDO', 'Recepción', 'MASGLO', 'unidad', 4, 0, NULL),
  ('MAGICO', 'REMOVEDOR', 'Recepción', 'NAGUEL', 'unidad', 3, 0, NULL),
  ('STAMPING', 'ESMALTE', 'Recepción', 'LA COSEDORA', 'unidad', 4, 0, NULL),
  ('MAGICO', 'REMOVEDOR', 'Recepción', 'MORADO', 'unidad', 1, 0, NULL),
  ('FORTALECEDORA', 'BASE', 'Recepción', 'MASGLO', 'unidad', 1, 0, NULL),
  ('POLISH', 'LIMA', 'Recepción', NULL, 'unidad', 10, 0, NULL),
  ('NARANJO', 'PALOS', 'Recepción', NULL, 'paquete', 1, 0, NULL),
  ('DECORACION', 'PINCELES', 'Recepción', 'TEMU', 'paquete', 1, 0, NULL),
  ('ACRILICO', 'PINCELES', 'Recepción', 'TEMU', 'unidad', 2, 0, NULL),
  ('PUSHER', 'HERRAMIENTAS', 'Recepción', 'TEMU', 'paquete', 1, 0, NULL),
  ('PUNZONES', 'HERRAMIENTAS', 'Recepción', 'TEMU', 'unidad', 3, 0, NULL),
  ('BROCAS', 'HERRAMIENTAS', 'Recepción', NULL, 'caja', 3, 0, NULL),
  ('AGUA', 'LIMAS', 'Recepción', NULL, 'paquete', 1, 0, NULL),
  ('SPONGE', 'LIMAS', 'Recepción', NULL, 'unidad', 9, 0, NULL),
  ('MORTERO', 'HERRAMIENTAS', 'Recepción', NULL, 'unidad', 1, 0, NULL),
  ('STAMPING', 'KIT', 'Recepción', NULL, 'unidad', 1, 0, NULL),
  ('LARGOS', 'MOLDES', 'Recepción', 'MIXCOCO', 'unidad', 1, 0, NULL),
  ('TOALLATAS', 'TOALLATAS', 'Recepción', 'TEMU', 'paquete', 1, 0, NULL),
  ('ALCOHOL', 'ALCOHOL', 'Recepción', NULL, 'unidad', 1, 0, NULL),
  ('PIEDRAS Y DIJES', 'DECORACION', 'Recepción', NULL, 'cajonera', 3, 0, NULL),
  ('XL', 'PRESS ON', 'Recepción', 'MIXCOCO', 'unidad', 1, 0, NULL),
  ('COFFIN', 'PRESS ON', 'Recepción', 'TEMU', 'unidad', 1, 0, NULL),
  ('CUADRADAS', 'PRESS ON', 'Recepción', 'TEMU', 'unidad', 1, 0, NULL),
  ('ALMENDRA', 'PRESS ON', 'Recepción', 'TEMU', 'unidad', 2, 0, NULL),
  ('TIPS', 'TIPS', 'Recepción', 'MIXCOCO', 'unidad', 1, 0, NULL),
  ('CANULAS', 'CANULAS', 'Recepción', 'QUENNIGTH', 'unidad', 1, 0, NULL),
  ('CILINDROS', 'HERRAMIENTAS', 'Recepción', 'TEMU', 'unidad', 1, 0, NULL),
  ('CAJA', 'BROCAS', 'Recepción', 'TEMU', 'unidad', 1, 0, NULL),
  ('PAPEL FOILD', 'DECORACION', 'Recepción', NULL, 'unidad', 1, 0, NULL),
  ('100/180', 'LIMAS', 'Recepción', 'FNAILS', 'unidad', 25, 0, NULL),
  ('TOP COAT', 'SEMIPERMANENTE', 'Recepción', 'MIXCOCO', 'unidad', 2, 0, NULL),
  ('RUBBER BASE COAT', 'SEMIPERMANENTE', 'Recepción', 'MIXCOCO', 'unidad', 4, 0, NULL),
  ('PROTEIN', 'SEMIPERMANENTE', 'Recepción', 'MIXCOCO', 'unidad', 2, 0, NULL),
  ('ESFOLIANTE', 'CREMAS', 'Recepción', NULL, 'unidad', 1, 0, NULL),
  ('REMOVEDOR TRADICIONAL', 'LIQUIDOS', 'Recepción', 'MAXIBELT', 'unidad', 1, 0, NULL),
  ('REMOVEDOR SEMI', 'LIQUIDOS', 'Recepción', 'ANTONELA', 'unidad', 1, 0, NULL),
  ('MONOMERO', 'LIQUIDOS', 'Recepción', 'ORGANIC', 'unidad', 2, 0, NULL),
  ('REMOVEDOR DE CALLOS', 'LIQUIDOS', 'Recepción', NULL, 'unidad', 1, 0, NULL),
  ('BLOOMING', 'FINALIZADOR', 'Recepción', 'MIXCOCO', 'unidad', 1, 0, NULL),
  ('FRE18', 'SEMIPERMANENTE', 'Recepción', 'MIXCOCO', 'unidad', 1, 0, NULL),
  ('FRE31', 'SEMIPERMANENTE', 'Recepción', 'MIXCOCO', 'unidad', 1, 0, NULL),
  ('SANGRE TORO', 'SECADO RAPIDO', 'Recepción', 'MASGLO', 'unidad', 3, 0, NULL),
  ('REBELDE', 'SECADO RAPIDO', 'Recepción', 'MASGLO', 'unidad', 1, 0, NULL),
  ('AUSENTE', 'SECADO RAPIDO', 'Recepción', 'MASGLO', 'unidad', 1, 0, NULL),
  ('RISUEÑA', 'SECADO RAPIDO', 'Recepción', 'MASGLO', 'unidad', 1, 0, NULL),
  ('BRILLO', 'TRADICIONAL', 'Recepción', 'MASGLO', 'unidad', 3, 0, NULL);
